version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root1234
      MYSQL_DATABASE: bonsaicorner
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - ratz-network
  bonsaicorner:
    image: ratzcom/bonsaicorner
    restart: always
    build: ./
    working_dir: /
    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/bonsaicorner?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 80:80
    command: mvn spring-boot:run -DskipTests
    depends_on:
      - db
    networks:
      - ratz-network
networks:
  ratz-network:
    driver: bridge